Madeleine add bbox filter
nens/LizardViewer pull request #27
Opened 2017-04-21 10:06 UTC by GeOdin

2017-04-24 09:29 UTC, jackieleng commented
nice

2017-04-24 10:22 UTC, jackieleng requested changes

2017-04-24 10:22 UTC, jackieleng commented on lizard_viewer.py
> +        if public_or_private is "private":
`is` compares references, use `==` (compares values)

2017-04-24 10:22 UTC, jackieleng commented on lizard_viewer.py
> +        if public_or_private is "private":
use `==` here also

2017-04-24 10:22 UTC, jackieleng commented on dockwidget.py
> +    def add_areafilters_to_combobox(self):
Is there a reason this is dynamically set and not via .iu file?

2017-04-24 10:22 UTC, jackieleng commented on lizard_viewer.py
> +        if list_of_assets != []:
It is more pythonic to do `if list_of_assets:`

2017-04-24 10:22 UTC, jackieleng commented on lizard_viewer.py
> +        if area_type == "Current view":
`"Current view"` is still kinda a magic string here, I think... 
Is probably okay for now, but it's maybe an idea to put this section into a function.

2017-04-24 10:22 UTC, jackieleng commented on utils/get_data.py
> +def get_bbox(iface):
What is the reason that this bbox function is in this module, while the other bbox related functions are in the geometry.py module?

2017-04-24 10:34 UTC, jackieleng commented on lizard_viewer.py
> +        area_index = area_combobox.currentIndex()
Just a though, `currentText` get the text right? Wouldn't that be more direct?

2017-04-25 07:53 UTC, GeOdin commented on utils/get_data.py
> +def get_bbox(iface):
I was in doubt whether to put it in the get_data module (getting the bbox as a form of getting data) or the geometry module.
The fact that you comment on this, shows that the geometry module is probably more logical.

2017-05-10 07:25 UTC, GeOdin commented on lizard_viewer.py
> +        area_index = area_combobox.currentIndex()
Good idea!

2017-05-10 14:09 UTC, jackieleng commented
:+1:

2017-05-10 14:10 UTC, merged