Madeleine interactive statusbar
nens/LizardViewer pull request #9
Opened 2017-02-13 09:11 UTC by GeOdin

The status bar is now interactive.

2017-02-14 14:20 UTC, GeOdin commented
![](https://github.trello.services/images/mini-trello-icon.png) [QGIS plug-in lizard (DockWidget) algemeen design [3]](https://trello.com/c/3arYe1K3/1304-qgis-plug-in-lizard-dockwidget-algemeen-design-3)

2017-02-16 16:50 UTC, jackieleng requested changes

2017-02-16 16:50 UTC, jackieleng commented on utils/set_dockwidget_gui.py
> +def status_bar_text(self, string):
Status bar variable names are not descriptive.

2017-02-17 22:03 UTC, jackieleng requested changes

2017-02-17 22:03 UTC, jackieleng commented on utils/set_dockwidget_gui.py
> +# -*- coding: utf-8 -*-
I think this whole logic should be moved to ``dockwidget.py``, and into the dockwidget class itself. Basically, you're operating on the dockwidget, and if that's the case, than we probably should group that logic together.

Additional points:
- you're repeating the same things three times, better to use a loop
- I think a more elegant solution is to do something like this (more reusable also):

```python
def set_status_bar_text(status_bar, text):
    status_bar.setText(text)
    status_bar.repaint()
```

- ``status_bar_text`` as a function name is unclear to me what it does. Only after reading the code would you understand that it sets all three status bars.

2017-02-17 22:03 UTC, jackieleng commented on lizard_downloader.py
> +        asset_type_caps = ASSET_TYPES[0][0].capitalize() + ASSET_TYPES[0][1:]
What's happening here? ``capitalize()`` already capitalizes the first letter, so shouldn't that be enough?

2017-02-17 22:03 UTC, jackieleng commented on lizard_downloader.py
>                  self.dockwidget = Ui_DockWidget()
``Ui_DockWidget()``  is also a pretty non-descriptive name

2017-02-20 15:53 UTC, jackieleng requested changes

2017-02-20 15:53 UTC, jackieleng commented on dockwidget.py
> +class LizardViewer_DockWidget(QtGui.QDockWidget, FORM_CLASS):
https://www.python.org/dev/peps/pep-0008/#class-names

Underscores are not necessary.

2017-02-20 15:53 UTC, jackieleng commented on lizard_downloader.py
> +        LizardViewer_DockWidget.set_all_status_bars_text(
please use: `self.dockwidget.set_all_status_bars_text`

2017-02-20 15:53 UTC, jackieleng commented on lizard_downloader.py
> +        LizardViewer_DockWidget.set_all_status_bars_text(
see above

2017-02-20 15:53 UTC, jackieleng commented on dockwidget.py
> +            for status_bar in status_bars]
please use a simple for loop

2017-02-20 16:34 UTC, merged